BEGIN;
ALTER TABLE video
ALTER COLUMN size TYPE BIGINT USING ROUND(size * 1000000)::BIGINT;

ALTER TABLE video
ADD COLUMN upload_id VARCHAR(255) NULL;

--UPDATE video AS v SET v.upload_id = 'qRe1.6V9u_8wX5A9ypU7nDGbcV9Ts3xzdF0FetkYgh56tZjGRs18MHCRc0hW9DQPECmwnoan0MUcGUG2wYASeN404AqdZRHHZvU6FV5.yrQ-';

--ALTER TABLE video
--ALTER COLUMN upload_id SET NOT NULL;

ALTER TABLE video
ADD CONSTRAINT fk_Vido_uploads
FOREIGN KEY (upload_id)
REFERENCES uploads(upload_id)
ON DELETE CASCADE;
COMMIT;