ALTER TABLE video
ALTER COLUMN title DROP NOT NULL,
ALTER COLUMN description DROP NOT NULL,
ALTER COLUMN master_playlist DROP NOT NULL,
ALTER COLUMN duration DROP NOT NULL,
ALTER COLUMN thumbnail DROP NOT NULL,
ALTER COLUMN resolutions DROP NOT NULL,
ALTER COLUMN categories DROP NOT NULL;